services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1403}
      POSTGRES_DB: ${DB_NAME:-TaskTrackerDb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tasktracker:
    image: tasktracker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasktracker_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-1403}
      - DB_NAME=${DB_NAME:-TaskTrackerDB}
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped

volumes:
  postgres_data: